apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: angular-tour-of-heroes

  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: {{ .Values.containerPort }}
