apiVersion: v1
kind: Service
metadata:
  name: flask
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: flask

  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: {{ .Values.flask.containerPort }}
